counter/urls.py
from django.conf.urls import url
from . import views

app_name = 'counter'

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),

    url(r'^counter/add/$', views.CounterCreate.as_view(), name='counter-add'),

    url(r'^counter/(?P<pk>[0-9]+)/$', views.CounterUpdate.as_view(), name='counter-update'),

    url(r'^counter/(?P<pk>[0-9]+)/delete/$', views.CounterDelete.as_view(), name='counter-delete'),

]

tally_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^counter/', include('counter.urls')),
]

counter/models.py
from django.db import models
from datetime import datetime
from django.core.urlresolvers import reverse

class CounterName(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('counter:details', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title + ' - ' + self.description



# class Chart(models.Model):
#    CounterName = models.ForeignKey(CounterName, on_delete=models.CASCADE)
#    file_type = models.CharField(max_length=10)


class NetCount(models.Model):
    CounterName = models.ForeignKey(CounterName, on_delete=models.CASCADE)
    numCount = models.IntegerField(default=0)
    time = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.CounterName.title) + ' = ' + str(self.numCount)

counter/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import CounterName, NetCount
NoneType = type(None)


class IndexView(generic.ListView):
    template_name = 'counter/index.html'

    def get_queryset(self):
        return CounterName.objects.all()


class DetailView(generic.DetailView):
    model = CounterName
    template_name = 'counter/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        counter = context['countername']
        context['latestCount'] = NetCount.objects.filter(CounterName__id=counter.id).last()
        return context


class CounterCreate(CreateView):
    model = CounterName
    fields = ['title', 'description']
    template_name = 'counter/counter_form.html'


class CounterUpdate(UpdateView):
    model = CounterName
    fields = ['title', 'description']
    template_name = 'counter/counter_form.html'


class CounterDelete(DeleteView):
    model = CounterName
    success_url = reverse_lazy('counter:index');

counter/templates/counter/base.html
<html>
<head>
    <title>Welcome</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%static 'counter/css/index.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'counter/css/details.css'%}"/>
</head>
<body>

<nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'counter:index' %}">TallyCounter</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav d-flex align-items-center">
      <li class="nav-item active">
        <a class="nav-link" href="#">Counter</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <form class="form-inline" style="margin:0px;" role="search"  action="#" method="get">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
      <ul class="navbar-nav ml-auto d-flex align-items-center">
          <li class="nav-item ">
        <a class="nav-link " href="{% url 'counter:counter-add' %}">Add Counter</a>
      </li>
       <li class="nav-item ">
        <a class="nav-link " href="#">Logoutr</a>
       </li>
      </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</html>

counter/templates/counter/counter_form.html
{% extends 'counter/base.html' %}

{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'counter/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>


{% endblock %}

counter/templates/counter/details.html
{% extends 'counter/base.html' %}
{% block body %}

    {% for counts in countername.netcount_set.all %}
    <li> Count at time - {{ counts.time}} = {{counts.numCount}}</li>
    {% endfor %}
    {{ latestCount.numCount }}</br>
<button type="button" class="btn btn-success col-md-2" id="increment" onclick="add_to_numCount();"><h4>+</h4></button>
<button type="button" class="btn btn-danger col-md-2"id="decrement" onclick="sub_from_numCount();"><h4>-</h4></button>
{% endblock %}

counter/templates/counter/form-template.html
{% for field in form %}
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
{%endfor%}

counter/templates/counter/index.html
{% extends 'counter/base.html' %}
{% block body %}

    <h3>Hello there</h3>
    <ul>
        {% for counter in object_list  %}
        <li><a href="{% url 'counter:details' counter.id %}">{{ counter.title }}</a>
        <form action="{% url 'counter:counter-delete' counter.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="counter_id" value="{{counter.id}}"/>
            <button type="submit" class="btn btn-default btn -sm">
                <i class="fa fa-trash"></i>
            </button>
        </form>
        </li>
        {% endfor %}
    </ul>

{% endblock %}